sudo: required
language: php
cache:
  - vendor
php:
  - '7.1'
before_script:
  - composer install -o --ignore-platform-reqs
after_success:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - "./etc/deploy.sh"
  - |
    if [ ! -z "$TRAVIS_TAG" ]; then
      aws s3 sync resources s3://resources.openfintech.io
      aws s3 sync resources/payment_methods s3://resources.openfintech.io/payment-methods
      aws s3 sync resources/payout_methods s3://resources.openfintech.io/payout-methods
      aws s3 sync resources/payment_providers s3://resources.openfintech.io/payment-providers
    fi
install:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer self-update && composer --version
script:
  - "./etc/validate.sh"
env:
  - secure: rn+oHlvnUqKXvTvzx5flnwm8H7/erGdX7mwUbiDw+prFMy+qPA431MWN0yr1Lc+Gz4hkhnpSnpWdU7VHRdOcf2y7xga3A6WbwUMaComqqvq6wCj1OkprbP+XHn4y7ZgCHSk24pWMaPwtemkQ1URhAUrybpZ3G2QCYBuU/FaCWxisjegVxYmibwj09CPzehM0xiQnuA9iVH6zuTerHsU9d/XNuuJzRYNlZltujTUWdY6WRYhwjCWzsseneO6O8I6pcdYUkUq8qapHAqSEYcxIScsnpfwgyDe0AMielT9N2tTeUeaWuhjkJ89kEC+iG3IV1oxr0pR8hRs4YUxDvQ6Vvsw3BhcwgoD8rLbAnYImZloUhR1ALC1qaufK7cxTxCC8w2EAR4RmCGUtLmKdKdPSsg1Exv7rzg5dsKZ94BP2ZxTJIl78lvTgMDupjsX/ykbTJmMqvPYk9SGJW9+saweUvudw0CpLHkWdDmlAj85517WCXK425WMnCGnMRtn14RRpVizsD8YZRDeCeXFMrAf7VLZ85JBwKrF01f06wq0nOCwFGbXvFs2rsw2vx9QAu4t9M1n+dBXpQsuD0R2va0cyBZLha1ZenRUk17stNuDVUjSIT73i+qXD94zQOa+ZZ7Yk6qS/NrT9Mrj9AI1tmws0v3OutOmo24RMLNq069cGsBw=
  - secure: CDDHUw67qtN62AARHtF1sbmuE+U9guthhM1D6jfKXPwz/WjQaL/ecPRF47D77GCPonu1nY13JVZDHYy0R0aSf0JXpR/Eg/Z1GEIPUYr0uLnqKgvqjPIgf8l/1OGZyjgIO/d+PjM5yF9itJBXej3STxP7CIVZSkdVogS6kZROBdAK1v5fVP2uLpFRydOlbyx9FtOFvZO5OyXnyiocUaxmDR1b7lyxC8UjuTSaZTb5Q1Rjs0f8gzIir5s6cgeoR60F5FbiC+Ti8hKWVuXiFTTugJ7s34UpvgP/eh6CVH8lgkV0ajUl6gmb4T3qNuEB8DY07hecJuSC8aLCf8JZj9kItJowFMYIHRNWxtukCDgc7Z+XIYB2qjmmgeXU+ZY6R7T1+4yCdoh1YHziM7oiNFFo24Ulh/1r46TQB1IMJ/Dt7XgodqglH8QDiwULbBDJuS0rM+4oguPrX+qMKZh9oZDc2CxMpWFGqsz2t/XmH7jnZpIMc9EQZvdfDCq7YxXPckcliuZ6KxHhJ/+7K0E+1J3gxgfgLpCtEBs6acDtAHbaTOgq2KpNnDeUPX48ngeIZwYIipwu9qnnn6GoduOb8WqmjrCziMQjFoyET6rVz/GgvKSyePZN58OcsTMmxaqHttGemUMXhas8pfwIIgUa1c/pCYsV9VQY1M3Wn+S/i89TvIA=
  - secure: FH54V+S/cQwc6W/sNzMHaoRnZLo9nfptHKlK8W1xLMV+Iu58f1WHgEHkGt6tZdb50urf23I6ov+/5ieFYDaya3bLe3O80tBPnue6nfhd9U+R8Si6cywzXFymmUWG1jR0jvQSRkPHVqYsE4r48thZujAn/ta7HUgOlzO9cuzT6HomJVho4GZrKQ2oPU7zOmT3Dp+iVcBIqGNDxi4riwQNOHopKYButg4qm0D7o6t8TEwT0HK4eBHjhzdvm2/RqdY3iuewj8HqZ9ZYRF6G7ypv0C9NRwK0W0Q5Gj7h5IpiLOSbL5gBU4aH5l36/iN4DABHKLSYuse2AwzEmU8YhoLUMs7Mwhje8iH2j9AzsZi+lGmC/9b5g2rlsQfLs/Nq6WEdhHxWJkfSXqtu6zr2U/UX69idZxlJqfcS+hTs2NEgq3RrUyLkAclgKaNdyz69VJ/t87Du6IuJkwR6f+ofI4dF7HF6CJYMvWg1CfphiU0pd/ASGvpJKAoQE6qNf1Mv9NuWDkm0Qi+wEir8pbIWY09E8hyrENtW5Ej9g9+zYLa1FAaAaClkm3H7aFw2mKze1J+JilkGvXyr5QqmgGoBlbfH2bE95GL09uiP9O0/GWcAY4tHBkyhHSzxM/qOBx13fxO4rAc//Ymnbl/4De8A9WJWHf2jbRxpQug30jaNBRSFZ3E=
