sudo: required
language: php
cache:
  - vendor
php:
  - '7.1'
before_script:
  - composer install -o --ignore-platform-reqs
after_success:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - "./etc/deploy.sh"
  - |
    if [ ! -z "$TRAVIS_TAG" ]; then
      aws s3 sync resources s3://resources.openfintech.io
      aws s3 sync resources/payment_methods s3://resources.openfintech.io/payment-methods
      aws s3 sync resources/payout_methods s3://resources.openfintech.io/payout-methods
      aws s3 sync resources/payment_providers s3://resources.openfintech.io/payment-providers
    fi
install:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer self-update && composer --version
script:
  - "./etc/validate.sh"
