sudo: required
language: php
cache:
- vendor
php:
- '7.1'
before_script:
- composer install -o --ignore-platform-reqs
after_success:
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
- "./etc/deploy.sh"
- "./etc/deploy-s3.sh"
install:
- export PATH="$HOME/.composer/vendor/bin:$PATH"
- travis_retry composer self-update && composer --version
script:
- "./etc/validate.sh"
env:
  matrix:
    secure: P5IkmmH3/wipzWTjrWBR8hdoC0kWZUuL7ucawRmNpIfrk4OXjeZ4PCW1xt2XZzdgygUZ8GFf5sPoEzwtPkfjHLl/8DXwLa6TUORLlPi3CV3mBspVoWeGvhhS6PPzbcQZuK2trtqVfdy9RPh0mW2G/66qT6IqmgSHGkTRDW1jCX9NUSRoWoGggRKPfIh7RmvuITj1Vr1PkTfV5bdXzrLmypXx4I2Jv8zG+TZWoxp0fb57qn1mQrvqARRmsUc2+feJqymbKeO+qXt2yq4a/q0WNTbkTm9Y2emVdnYECFI354DK0FNkxFp2Zy+cMNL0RuNoHGCeutWLMWpU6KbsY21nz/oAGyd/o5/qzdbP+5J2ikkUDuG7Z/koNeoII5cXHNv7tpq40xc52osc0c5A+kGi2hevT52Yc6IWPx5k5fITyiM/3yWldiZWf1knJOIXiPbUXS1T2GlrFXneAEqAEfDaJTbMa/cQplFqh/zDgQwpVFITRXUzTt2I2BOi3D1flvujVG7RYxAPzt0BYGhetq5HA2cww2uhC8ZaCIsftk7nmJ7NX+jUZV7sHYATAQ2N1bFX7ol+M4EzFe1RLzRDbQH5WxzpQAfTl1kOdWfmJ2rCcH0DiawoEHHkcBlqb+JD70H2jE90OyP6/pUquG0PMEi0wvo7tjcLW2r6QgV068XJ+Qc=
