sudo: required
language: php
cache:
  - vendor
php:
  - '7.1'
before_script:
  - composer install -o --ignore-platform-reqs
after_success:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - "./etc/deploy.sh"
  - "./etc/deploy-s3.sh"
install:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer self-update && composer --version
script:
  - "./etc/validate.sh"

matrix:
  include:
    - language: python
      sudo: false
      language: python
      install:
      - pip install mkdocs mkdocs-material
      script:
      - git clean -f -d -x;
      - mkdocs build
      deploy:
          provider: script
          script: if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then ./deploy.sh; else echo "PR skip deploy"; fi
          on:
            branch: master

env:
  matrix:
    secure: 42322482018bd4d8b35c04660d75fa2ae3d81c45